blog/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from .views import blogPageView, postDetailView, addPostView

# for blog views
urlpatterns = patterns('blog.views',
    
    #for the blog view
    url(r'^/$', blogPageView.as_view(), name='main'),
    url(r'^/add/$', addPostView.as_view(), name='post_add'),
    url(r'^/(?P<slug>[\w-]+)/$', postDetailView.as_view(), name='post_detail'),
)

instructor_website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import loginView, homePage, mailingListForm, mailingListSuccess

admin.autodiscover()

#base home
urlpatterns = patterns('instructor_website.views',

    url(r'^$', homePage.as_view(), name='home'),
    url(r'^mailing-list/', mailingListForm.as_view(), name='mailing-list'),
    url(r'^mailing-list-success/', mailingListSuccess.as_view(), name='mailing-list-success'),
    url(r'^blog', include("blog.urls", namespace='blog')),
    url(r'^login/', loginView.as_view(), 'django.contrib.auth.views.login'),
        
    #admin access for postgres
    url(r'^admin/', include(admin.site.urls)),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.forms import ModelForm

from markdown import markdown

from .lists import COUNTRIES, STATES

# DB models.
########################
## POST MODEL
########################
class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    author = models.ForeignKey(User, related_name="posts")
    content = models.TextField()
    image = models.ImageField(upload_to="post_images/", blank=True)
    published = models.BooleanField(default=True)
    
    class Meta:
        ordering = ["-created_at", "title"]
    
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return ("blog:post_detail", (), {"slug": self.slug})

        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
        
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')


########################
## RESORT MODEL
########################        
class Resort(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=4, choices=COUNTRIES)
    state = models.CharField(max_length=3, choices=STATES)
    
    class Meta:
        ordering = ["country", "state", "name"]
        
    def __unicode__(self):
        return self.name

        
########################
## PROFILE MODEL
########################    
class Profile(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    username = models.ForeignKey(User, related_name="profile", unique=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    slug = models.SlugField(max_length=512, blank=True, default='')
    country = models.CharField(max_length=255, choices=COUNTRIES)
    resort = models.ForeignKey(Resort, related_name="user_profile")
    description = models.TextField()
    markdown_description = models.TextField('Body', help_text='Use markdown for publishing')
    contact_info = models.TextField()
    contact_phone = models.CharField(max_length=255)
    contact_email = models.EmailField(max_length=255, unique=True)
    
    class Meta:
        ordering = ["lastname", "firstname"]
        
    def __unicode__(self):
        return self.firstname + self.lastname
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.firstname + self.lastname + self.resort)
        import markdown
        self.description = markdown.markdown(self.markdown_description)
        super(Profile, self).save(*args, **kwargs)
        

########################
## FOLLOWER MODEL
######################## 

class Follower(models.Model):
    follow_date = models.DateTimeField(auto_now_add=True, editable=False)
    email = models.EmailField(max_length=255, unique=True)
    firstname = models.CharField(max_length=255, blank=True, default='')
    lastname = models.CharField(max_length=255, blank=True, default='')
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ["-follow_date", "email"]
    
    def __unicode__(self):
        return self.email
    
class FollowerForm(ModelForm):
    class Meta:
        model = Follower
        fields = ('firstname', 'lastname', 'email')

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, FormView, TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy

from .models import Post, PostForm

class publishedPostMixin(object):
    def get_queryset(self):
        queryset = super(publishedPostMixin, self).get_queryset()
        return queryset.filter(published=True)    

class blogPageView(publishedPostMixin, ListView):
    model = Post
    template_name = 'blog.html'
        
class addPostView(CreateView):
    form_class = PostForm
    template_name = 'blog/add_post.html'
    success_url = reverse_lazy('blog:main')
    
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.instance.author = self.request.user
        return super(addPostView, self).form_valid(form)
    
class postDetailView(publishedPostMixin, DetailView):
    model = Post

instructor_website/views.py
from django.shortcuts import render_to_response
from django.views.generic import TemplateView, DetailView, FormView, View, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth import login
from django import forms

from django.core.urlresolvers import reverse, reverse_lazy
from blog.models import Profile, Follower, FollowerForm

class mailingListForm(CreateView):
    form_class = FollowerForm
    template_name = 'mailingList.html'
    success_url = reverse_lazy('mailing-list-success')
    
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super(mailingListForm, self).form_valid(form)

class mailingListSuccess(TemplateView):
    template_name = 'mailingListSuccess.html'

class homePage(TemplateView):
    template_name = 'home.html'
    
    def get_context_data(self, **kwargs): 
        context = super(homePage, self).get_context_data(**kwargs)
        profile = Profile.objects.get(pk=1)
        context["profile"] = profile
        context['form'] = mailingListForm()
        return context
    
    def get(self, request, *args, **kwargs):
        return super(homePage, self).get(request, *args, **kwargs)


# TODO: Login screen
class loginView(FormView):
    template_name = 'login.html'
    

    

instructor_website/templates/_layouts/header.html
<!DOCTYPE html>

<!-- Le javascript -->
<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- Bootstrap jQuery plugins compiled and minified -->
<script src="{{ STATIC_URL }}js/bootstrap.js" /> </script>
<!-- CAROUSEL SCRIPT -->
<script>
    $(document).ready(function() {
        $('.carousel').carousel({
            interval: 3000
        });
    });
</script>
<!-- -->
<script>
    
</script>

<!-- AUTO SCROLL SCRIPT -->
<script>
    $(document).ready(function() {
        var hashTagActive = "";
        $(".scroll").click(function (event) {
            if(hashTagActive != this.hash) { //this will prevent if the user click several times the same link to freeze the scroll.
                event.preventDefault();
                //calculate destination place
                var dest = 0;
                if ($(this.hash).offset().top > $(document).height() - $(window).height()) {
                    dest = $(document).height() - $(window).height();
                } else {
                    dest = $(this.hash).offset().top;
                }
                //go to destination
                $('html,body').animate({
                    scrollTop: dest
                }, 2000, 'swing');
                hashTagActive = this.hash;
            }
        });
    });
</script>

<!-- Facebook SDK for functions -->
<div id="fb-root"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) 
            return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }
    (document, 'script', 'facebook-jssdk'));
</script>

<!-- DISQUS THREAD JS -->
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'skiwithsam'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

<!-- Remove fade when in IE, known bug with bootstrap using modals-->
<script type="text/javascript">
    $(function() {
        if ($.browser.msie) {
            $('.modal').removeClass('fade');
        }
    });
</script>


<head>
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" type="image/x-icon"/>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block page_title %}{% endblock %} | Ski with Sam</title>

    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}css/custom.css" rel="stylesheet" />
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" />
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
    </style>
</head>

{% block content %}{% endblock %}

instructor_website/templates/_layouts/navbar.html
    <div class="navbar-wrapper">
        <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation" id="mainNavbarId">
            <div class="container-fluid">
            
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-id">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p><a class="navbar-brand" href="#">Sam Bergeron
                    <extra-small>Ski instructor</extra-small></a>
                    </p>
                </div>

                <div class="navbar-collapse collapse" id="navbar-collapse-id">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="hidden-xs hidden-sm"><a class="scroll" href="{{ profileLink }}">Profile</a>
                        </li>
                        <li class="hidden-xs hidden-sm"><a class="scroll" href="{{ contactLink }}">Contact</a>
                        </li>
                        <li><a href="{% url 'blog:main' %}">Blog</a>
                        </li>
                    </ul>
                
                </div>
            </div>
        </nav>
    </div>

instructor_website/templates/blog.html
{% extends "_layouts/header.html" %}

{% block page_title%}Blog{% endblock%}

{% block content %}
<body data-spy="affix" data-offset="20" data-offset-bottom="200" id="top">


    {% include "_layouts/navbar.html" with profileLink='/#profile' contactLink='/#contact' %}
    
    <div class="container container-fluid">
        
        <div class="col-md-9 col-sm-12 col-xs-12">
            <div class="lead"></div>
            {% for post in post_list %}
            <div class="row" id="{{ post.slug }}">
            
                {% if forloop.counter|divisibleby:2 %}
                <div class="col-md-5">
                    <br/><br/><br/>
                    <img src="{{ post.image.url }}" width="100%">
                    <h5 class="text-right"><small>- Posted on {{ post.updated_at }} by {{ post.author }} </small></p>
                </div>
                {% endif %}
            
                <div class="col-md-7">
                    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    <p>{{ post.content }}</p>
                    <!-- Share button here -->
                    <div>
                        <div class="fb-share-button" data-href="{{ post.get_absolute_url }}" data-layout="button_count"></div>
                        <a href="{{ post.get_absolute_url }}#disqus_thread"><p class="text-right">Comment</h4></a>
                    </div>
                </div>
                
                {% if forloop.counter0|divisibleby:2 %}
                <div class="col-md-5">
                    <br/><br/><br/>
                    <img src="{{ post.image.url }}" width="100%">
                    <h5 class="text-right"><small>- Posted on {{ post.updated_at }} by {{ post.author }} </small></p>
                </div>
                {% endif %}
                
                
            </div>

            <hr/>
            {% endfor %}
            <p>
                <h5 class="text-right"><a class="scroll" href="#top">Top</a></h5>
            </p>
        </div>
        
        <div class="col-md-3">
            <div class="hidden-xs hidden-sm">
                <div class="lead"></div>
                <h2>Latest News</h2>
                <ul>
                    {% for post in post_list %}
                    <li><a class="scroll" href="#{{ post.slug }}">{{ post.title }}</a></li>
                    {% empty %}
                    <li>Sorry, we haven't started posting yet!</li>
                    {% endfor %}
                </ul>
                </hr>
                <!-- www.intagme.com -->
                <iframe src="http://www.intagme.com/in/?u=c2FtMTB0aHB8aW58MTAwfDJ8Nnx8eWVzfDV8dW5kZWZpbmVkfHllcw==" 
                allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:230px; height: 690px" ></iframe>
            </div>    
            
            {% if user.is_authenticated %}
            <p class="text-right">
                <a href="{% url 'blog:post_add' %}">New Post
                    <span class="glyphicon glyphicon-add"/>
                </a>
            </p>
            {% endif %}
        </div>
    </div>
    
</body>
{% endblock%}
    

instructor_website/templates/blog/add_post.html
{% extends "_layouts/header.html" %}

{% block page_title%}Blog{% endblock%}

{% block homeLink %} {% url 'home' %} {%endblock%}
{% block profileLink %} {% url 'home' %}#profile {%endblock%}
{% block contactLink %} {% url 'home' %}#contact {%endblock%}
{% block blogLink %} {% url 'blog:main' %} {%endblock%}

{% block content %}

    {% include '_layouts/navbar.html' %}

    <div class="container container-fluid">
        <div class="row">
            <h1>New Post</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <button type="submit">Post</button>
            </form>
        </div>
    </div>
    
{% endblock %}

instructor_website/templates/blog/post_detail.html
{% extends "_layouts/header.html" %}

{% block page_title%}{{post.title}}{% endblock%}

{% block content %}

    <div class="container container-fluid">
        <div class="container" id="mobile-spacer">
            <div class="row" id="{{ post.slug }}">
                <p class="text-right"><a href="{% url 'blog:main' %}" class="glyphicon glyphicon-arrow-left">&nbsp;Back</a></p>
                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                <p class="text-justify">{{ post.content }}</p>
                <div class="container">
                    <img src="{{ post.image.url }}" width="100%">
                </div>
                <h5 class="text-right"><small>- Posted on {{ post.updated_at }} by {{ post.author }} </small></p>
            </div>
        </div>
        
        <div id="disqus_thread"></div>
    </div>

{% endblock %}

instructor_website/templates/home.html
{% extends "_layouts/header.html" %}

{% block page_title%} Home {% endblock%}

{% block content %}
<!-- No need for the dataspy... later maybe
 <body data-spy="scroll" data-offset="60" data-target=".navbar"> -->
<body>

    {% include "_layouts/navbar.html" with  profileLink="#profile" contactLink="#contact" %}
    
    <!--  Carousel -->
    <div id="this-carousel-id" class="carousel slide" data-ride="carousel">

        <div class="carousel-inner">
            <div class="item active">
                <img class="img-responsive" width="100%" src="{{ STATIC_URL }}img/dobson.jpg" alt="Slide 1" />
                <div class="carousel-caption">
                    <p class="hidden-sm hidden-xs">Mount Dobson, New Zealand</p>
                </div>
            </div>
            <div class="item">
                <img class="img-responsive" width="100%" src="{{ STATIC_URL }}img/brownShorts.jpg" alt="Slide 2" />
                <div class="carousel-caption">
                    <p class="hidden-sm hidden-xs">Revelstoke, British Columbia, Canada</p>
                </div>
            </div>
            <div class="item">
                <img class="img-responsive" width="100%" src="{{ STATIC_URL }}img/springfield.jpg" alt="Slide 3" />
                <div class="carousel-caption">
                    <p class="hidden-sm hidden-xs">Springfield, New Zealand</p>
                </div>
            </div>
            <div class="item">
                <img class="img-responsive" width="100%" src="{{ STATIC_URL }}img/banff.jpg" alt="Slide 4" />
                <div class="carousel-caption">
                    <p class="hidden-sm hidden-xs">Lake Louise, Alberta, Canada</p>
                </div>
            </div>
        </div>
        <!-- .carousel-inner -->
        <!--  next and previous controls here
              href values must reference the id for this carousel -->
        <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
    </div>
    <!-- .carousel -->
    <!-- end carousel -->

    <p class="lead lead-large" />

    <div class="container container-fluid" id="profile">

        <hr/>
        
        <div class="row">
            
            <div class="col-md-4 col-xs-12 col-sm-12">
                <br><br>
                <ul class="img-list">
                    <li>
                        <img id="profilePic" class="grayscale-hover" src="{{ STATIC_URL }}img/SamTop.jpg" width="100%"/>
                            <span class="text-content"><span>Sam skiing in the monahsees</span></span>
                    </li>
                </ul>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="container-fluid textPanel">
                    <p class="text-left">
                        <h2 class="text-left" style="color: #FCFCFC;"><b>{{ profile.firstname }}&nbsp;{{ profile.lastname }}</b></h2>
                        <p class="text-left">{{ profile.description | safe }} </p>
                        </p>
                    </p>
                </div>
            </div>
        </div>

        <br/>
        
        <!-- VIDEO SECTION FOR MOBILE ONLY -->
        <div class="hidden-lg hidden-md">
            <div class="panel-heading" role="tab" id="videoHeading">
                <h3><a role="button" data-toggle="collapse" data-parent="#accordion" href="#videoCollapse" aria-expanded="true" aria-controls="videoCollapse">
                   <span class="glyphicon glyphicon-expand"></span>&nbsp;&nbsp;Click here for some videos
                </a>
                </h3>
            </div>
            <div id="videoCollapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="videoHeading">
              <div class="panel-body">
                  <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="//player.vimeo.com/video/106988105?color=008cba"></iframe>
                    </div>
                
                <br/>
                <div class="embed-responsive embed-responsive-4by3">
                        <iframe class="embed-responsive-item" src="//player.vimeo.com/video/104672627?color=008cba"></iframe>
                    </div>
              </div>
            </div>
        </div>
        
        <div class="row hidden-xs hidden-sm">
            <div class="container container-fluid">
                <h3><a role="button" data-toggle="modal" data-target="#modalFirstVid">Little video?&nbsp;&nbsp;<span class="glyphicon glyphicon-expand"></span></a>
                    <a class="pull-right" role="button" data-toggle="modal" data-target="#modalSecondVid">Curious about tree skiing lessons?&nbsp;&nbsp;<span class="glyphicon glyphicon-expand"></span></a>
                </h3>
            </div>
        </div>

        <br class="hidden-xs hidden-sm"/>

        <div class="row" id="contact">
            <div class="col-md-5 col-sm-12 col-xs-12">
                <p clas="lead" />
                <div class="hidden-sm hidden-xs" id="spacing">
                    <br/>
                    <br/>
                    <br/>
                </div>
                <blockquote>
                    <address class="inline-block">
                        <strong>{{ profile.firstname }}&nbsp;{{ profile.lastname}}</strong><br/>
                        Canadian phone :<br/>
                        <span class="glyphicon glyphicon-earphone"/>: 1 (514) 531-3944<br/>
                        <a href="mailto:{{profile.contact_email}}">{{ profile.contact_email }}</a><br/>
                        <small>For bookings or inquiries</small><br/>
                    </address>
                    Classes depending on availability,
                    <br/>Contact <a href="http://www.revelstokemountainresort.com">RMR</a> front desk for bookings
                    <br/>
                    <span class="glyphicon glyphicon-earphone" />: 1 (250) 814-5060<br/>
                    <br/>
                        
                </blockquote>
            </div>
            <div class="col-md-7 col-sm-12 col-xs-12">
                <img src="{{ STATIC_URL }}img/templeComp.jpg" width="100%"/>
            </div>
        </div>
    </div>
    
    <br/>
    
    <div class="footer">
        <div class="container">
            
            <br>
            <div class="row">
                <div class="col-lg-offset-3 col-lg-5">
                    <p class="text-center">
                        Stay up to date with Sam and his adventures by submiting your email!
                        We'll send you blog updates and updates on where Sam is skiing now so you can keep up, or try to catch up.
                        <a href="{% url 'mailing-list' %}">Get News!</a>
                    </p>
                </div>
                <div class="col-lg-4 text-right">
                    <a class="facebook" href="https://www.facebook.com/samuel.bergeron">
                    </a>
                    &nbsp;
                    <a class="instagram" href="http://instagram.com/sam10thp?ref=badge">
                    </a>
                </div>
                <br>
            </div>
        
        <hr>
            <footer>
                <p><small>&copy; Samuel Bergeron 2014</small></p>
                <br><br>
            </footer>
            
        </div>
    </div>
    
<!-- MODALS -->
    <!-- first video modal -->    
    <div class="modal fade" id="modalFirstVid" tabindex="-1" role="dialog" aria-labelledby="modalFirstVid" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h5 class="text-center">Just an other winter month in Revelstoke</h1>
                </div>
                <div class="modal-body">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="//player.vimeo.com/video/106988105?color=008cba"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal -->
    
    <!-- second video modal -->
    <div class="modal fade" id="modalSecondVid" tabindex="-1" role="dialog" aria-labelledby="modalSecondVid" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h5 class="text-center">A little tree lesson on a sunny day</h1>
                </div>
                <div class="modal-body">
                    <div class="embed-responsive embed-responsive-4by3">
                        <iframe class="embed-responsive-item" src="//player.vimeo.com/video/104672627?color=008cba"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal -->
    
</body>
        
</html>


{% endblock %}

instructor_website/templates/mailingList.html
{% extends "_layouts/header.html" %}

{% block page_title%}Mailing List{% endblock%}

{% block content %}

    {% include '_layouts/navbar.html' %}

    <div class="container container-fluid">
        <div class="row">
            <h1>Get News!!</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <button type="submit">Follow us!</button>
            </form>
        </div>
    </div>
    
{% endblock %}

instructor_website/templates/mailingListSuccess.html
{% extends "_layouts/header.html" %}

{% block page_title%}Mailing List{% endblock%}

{% block content %}

    {% include '_layouts/navbar.html' %}

    <div class="container container-fluid">
        <div class="row">
            <h1>Thanks for Following!</h1>
            <h3>Just follow the link to head back to the main page, 
                <a href="{% url 'home' %}">here</a>.
            </h3>
        </div>
    </div>
    
{% endblock %}